apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "0 * * * *" # every hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-cronjob
            image: jbrable/my-cronjob:latest
          restartPolicy: OnFailure
