apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops
spec:
  project: default
  source:
1    repoURL: https://github.com/JulesBrable/mlops.git
2    targetRevision: main
    path: deployment
  destination:
    server: https://kubernetes.default.svc
3    namespace: user-jbrablx
  syncPolicy:
    automated:
      selfHeal: true