apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops
spec:
  project: default
  source:
    repoURL: https://github.com/JulesBrable/mlops.git
    targetRevision: main
    path: k8s/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: user-jbrablx
  syncPolicy:
    automated:
      selfHeal: true