name: Construction image Docker

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push for cronjob
      uses: docker/build-push-action@v5
      with:
        context: ./cronjob
        push: true
        tags: jbrable/my-cronjob:latest
    -
      name: Build and push for app
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: jbrable/mlops:v1.5.4
